### ISSUE TITLE
Problem to connect to cluster

### ISSUE THREAD

**Issue by justjoheinz** [SahilKang/cl-rdkafka#70]
When I try the simple demo snippets in the README or run the test suite using docker I will get errors like this one:

```
test-test-1  | TEST/HIGH-LEVEL/ADMIN::CREATE-PARTITIONS-WITH-PRODUCER%3|1675427948.113|FAIL|rdkafka#consumer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.22.0.3:9092 failed: Connection refused (after 0ms in state CONNECT)
test-test-1  | %3|1675427948.113|ERROR|rdkafka#consumer-1| [thrd:kafka:9092/bootstrap]: 1/1 brokers are down
test-test-1  | %3|1675427948.118|FAIL|rdkafka#producer-2| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.22.0.3:9092 failed: Connection refused (after 0ms in state CONNECT)
test-test-1  | Unhandled CL-RDKAFKA:KAFKA-ERROR in thread #<SB-THREAD:THREAD "cl-rdkafka" RUNNING
test-test-1  |                                               {1004234173}>:
test-test-1  |   Expected event-type `1`, not `8`
test-test-1  |
test-test-1  | Backtrace for: #<SB-THREAD:THREAD "cl-rdkafka" RUNNING {1004234173}>
```

I am working on an M1 Mac with librdkafka installed via homebrew. I can reach the kafka instance running inside of docker with command line tools such as kafka-topics --bootstrap-servers 127.0.0.1:9092 --list etc. But not via Common Lisp. Any ideas?

**Comment by justjoheinz** [comment]
Additional info:

it seems that the code never returns from `( kf:flush producer)` using the producer example from the readme.

**Comment by SahilKang** [comment]
The error you're seeing looks to be something from librdkafka: the producer is getting an [error event](https://github.com/confluentinc/librdkafka/blob/076405ed3255baed78a1452aa5638642a35a2d87/src/rdkafka.h#L5256) instead of an expected delivery report.

If this is happening consistently, then I think the best way to debug would be to put together a minimal C program that accomplishes the same thing as the README producer example. That should clearly narrow it down to either cl-rdkafka or librdkafka

**Comment by svetlyak40wt** [comment]
I've also experienced such error. My setup was: Kafka running in the docker container:

```
version: '3.4'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.0
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2183
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.2.0
    container_name: broker
    restart: always
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9192:9192"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2183'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9192,PLAINTEXT_INTERNAL://broker:29192
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
```

When I do 'docker-compose up' and then use kafkacat to produce messages, I get this error:

```
kafkacat -P -b localhost:9192 -t foo
%3|1731662361.422|FAIL|rdkafka#producer-1| [thrd:broker:9192/1]: broker:9192/1: Failed to resolve 'broker:9192': Temporary failure in name resolution (after 2ms in state CONNECT)
%3|1731662362.425|FAIL|rdkafka#producer-1| [thrd:broker:9192/1]: broker:9192/1: Failed to resolve 'broker:9192': Temporary failure in name resolution (after 2ms in state CONNECT, 1 identical error(s) suppressed)
%3|1731662397.504|FAIL|rdkafka#producer-1| [thrd:broker:9192/1]: broker:9192/1: Failed to resolve 'broker:9192': Temporary failure in name resolution (after 2ms in state CONNECT, 8 identical error(s) suppressed)
```

When I run this consumer from Lisp:

I get this error, which is similar to @justjoheinz error, but originated from `CL-RDKAFKA::PROCESS-SEND-EVENT`:

```
Expected event-type `1`, not `8`
   [Condition of type CL-RDKAFKA:KAFKA-ERROR]

Restarts:
 0: [TRANSFER-ERROR] Transfer this error to a dependent thread, if one exists.
 1: [KILL-ERRORS] Kill errors in workers (remove debugger instances).
 2: [ABORT] abort thread (#<THREAD tid=3295 "cl-rdkafka" RUNNING {10042F1073}>)

Backtrace:
 0: (CL-RDKAFKA::ASSERT-EXPECTED-EVENT #.(SB-SYS:INT-SAP #X7F99DC004EB0) 1)
      Locals:
        EXPECTED = 1
        RD-KAFKA-EVENT = #.(SB-SYS:INT-SAP #X7F99DC004EB0)
 1: (CL-RDKAFKA::PROCESS-SEND-EVENT #.(SB-SYS:INT-SAP #X7F99DC004EB0) #S(LPARALLEL.CONS-QUEUE:CONS-QUEUE :IMPL #S(LPARALLEL.RAW-QUEUE:RAW-QUEUE :HEAD #1=(#) :TAIL #1#) :LOCK #<SB-THREAD:MUTEX "Anonymous l..
      Locals:
        QUEUE = #S(LPARALLEL.CONS-QUEUE:CONS-QUEUE ..)
        RD-KAFKA-EVENT = #.(SB-SYS:INT-SAP #X7F99DC004EB0)
 2: (CL-RDKAFKA::PROCESS-EVENTS #.(SB-SYS:INT-SAP #X7F99F000A8B0))
      Locals:
        EVENT = #.(SB-SYS:INT-SAP #X7F99DC004EB0)
        RD-KAFKA-QUEUE = #.(SB-SYS:INT-SAP #X7F99F000A8B0)
 3: ((FLET "WITHOUT-INTERRUPTS-BODY-" :IN SB-THREAD::CALL-WITH-MUTEX))
 4: (SB-THREAD::CALL-WITH-MUTEX #<FUNCTION (FLET SB-THREAD::WITH-MUTEX-THUNK :IN CL-RDKAFKA::POLL-LOOP) {7F99F85C643B}> #<SB-THREAD:MUTEX "address->queue-lock" taken owner=cl-rdkafka>)
 5: (CL-RDKAFKA::POLL-LOOP)
      Locals:
        RD-KAFKA-QUEUE = #.(SB-SYS:INT-SAP #X7F99F000A8B0)
```

This happens because I'm running producer outside of the docker and it does not know how to resolve `broker` host.

Number `8` corresponds to a `rd-kafka-event-error` constant. Probably `assert-expected-event` function can be improved to show a error message from kafka using `(cl-rdkafka/ll:rd-kafka-event-error-string cl-rdkafka::rd-kafka-event)`.

## Solution

Edit `/etc/hosts` and add such line:

```
127.0.0.1 localhost broker
```
